name: Newsfile

on:
  pull_request:
    branches: [ main ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: # Needed for comparison
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install towncrier==21.9.0
      - name: ":newspaper: Newsfile"
        run: python3 -m towncrier.check --compare-with=origin/main
