on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  percy:
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: https://npm.pkg.github.com/
      - run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm install
          npm install concurrently http-server wait-on
          npx browserslist@latest --update-db
        env:
          # also other environment variable
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Storybook
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          yarn build-storybook --quiet
      - run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006" \
            "echo \"Starting test\" && npx wait-on -l tcp:127.0.0.1:6006 && npm run percy"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
