on:
  push:
    branches:
      - main

jobs:
  percy:
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://npm.pkg.github.com/
      - run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm install
          npx browserslist@latest --update-db
        env:
          # also other environment variable
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm run storybook -- --no-open &
          sleep 60
          npm run percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
